---
- name: Install prerequisite packages for repositories
  ansible.builtin.apt:
    name:
      - software-properties-common
      - python3-apt
    state: present
    update_cache: yes

- name: Update apt cache and install prerequisites
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - git
      - acl
      - openssl
      - mysql-server
      - python3-certbot-nginx
    update_cache: yes

- name: Create directory for apt keyrings
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Add Docker's official GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'
    force: true

- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    update_cache: yes

- name: Install Docker Engine and plugins
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    update_cache: yes
