# frontend/Dockerfile
FROM nginx:alpine

# Copy Nginx template config for game
COPY nginx.conf /etc/nginx/nginx.conf

# Keep stock default.conf + also mount your own if needed
# If you want to replace, COPY it here:
# COPY default.conf /etc/nginx/conf.d/default.conf

# Copy static frontend files
COPY . /usr/share/nginx/html

EXPOSE 80 443

CMD ["nginx", "-g", "daemon off;"]
