# This workflow name will appear in the Actions tab
name: Docker Multi-Service CI/CD

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    # This output makes the generated tag available to other jobs
    outputs:
      version: ${{ steps.meta-frontend.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract Frontend Docker metadata
        id: meta-frontend
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}-frontend
          tags: |
            # Tag with the git tag on a tag push, e.g., v1.2.3
            type=ref,event=tag
            # Tag with the short commit SHA as a fallback for other events
            type=sha,prefix=,format=short
          flavor: |
            latest=false

      - name: Extract Backend Docker metadata
        id: meta-backend
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}-backend
          tags: |
            type=ref,event=tag
            type=sha,prefix=,format=short
          flavor: |
            latest=false
          
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./Docker
          file: ./Docker/Dockerfile.frontend
          push: true
          tags: ${{ steps.meta-frontend.outputs.tags }}
          labels: ${{ steps.meta-frontend.outputs.labels }}

      - name: Build and push Backend image
        uses: docker/build-push-action@v5
        with:
          context: ./Docker
          file: ./Docker/Dockerfile.backend
          push: true
          tags: ${{ steps.meta-backend.outputs.tags }}
          labels: ${{ steps.meta-backend.outputs.labels }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push # This job depends on the build-and-push job
    name: Deploy to EC2
    steps:
      - name: Deploy to EC2 instance
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            # Use the version tag passed from the build job
            export IMAGE_TAG=${{ needs.build-and-push.outputs.version }}
            
            # Navigate to the app directory where your docker-compose.yml is
            cd /path/to/your/app

            # Pull the specific image tags from Docker Hub
            docker-compose pull

            # Stop and remove the old containers
            docker-compose down

            # Start the services with the new versioned images
            docker-compose up -d
